PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>

SELECT DISTINCT ?iri ?text
WHERE { 
    { ?iri rdfs:label ?text }
    UNION
    { ?iri skos:prefLabel ?text }
    UNION
    { ?iri skosxl:prefLabel ?label . ?label skosxl:literalForm ?text . }
}